### ISSUE TITLE
Compilation in Arduino 1.6.0?

### ISSUE THREAD

**Issue by CanisLatrans** [RedBearLab/nRF8001#5]
Any chance that you can get the code to compile in the new 1.6.0 environment?
Arduino: 1.6.0 (Windows 8), Board: "Arduino Uno"

D:\Arduino\libraries\RBL_nRF8001\RBL_nRF8001.cpp:25:23: error: setup_msgs causes a section type conflict with __c
 static hal_aci_data_t setup_msgs[NB_SETUP_MESSAGES] PROGMEM = SETUP_MESSAGES_CONTENT;

                       ^
In file included from D:\Arduino\libraries\BLE/hal_platform.h:32:0,
                 from D:\Arduino\libraries\BLE/lib_aci.h:34,
                 from D:\Arduino\libraries\RBL_nRF8001\RBL_nRF8001.h:17,
                 from D:\Arduino\libraries\RBL_nRF8001\RBL_nRF8001.cpp:14:
D:\Arduino\hardware\arduino\avr\cores\arduino/WString.h:38:74: note: '__c' was declared here
 #define F(string_literal) (reinterpret_cast<const __FlashStringHelper *>(PSTR(string_literal)))
                                                                          ^
D:\Arduino\libraries\RBL_nRF8001\RBL_nRF8001.cpp:388:32: note: in expansion of macro 'F'
                 Serial.println(F("Advertising started"));

                                ^
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by webventil** [comment]
I got the same problem using Arduino 1.6.0 on Mac OS X. Please fix!

Arduino: 1.6.0 (Mac OS X), Board: "Arduino Uno"

Build options changed, rebuilding all
/Users/atf/Documents/Arduino/libraries/RBL_nRF8001/RBL_nRF8001.cpp:25:23: error: setup_msgs causes a section type conflict with __c
 static hal_aci_data_t setup_msgs[NB_SETUP_MESSAGES] PROGMEM = SETUP_MESSAGES_CONTENT;
                       ^
In file included from /Users/atf/Documents/Arduino/libraries/BLE/hal_platform.h:32:0,
                 from /Users/atf/Documents/Arduino/libraries/BLE/lib_aci.h:34,
                 from /Users/atf/Documents/Arduino/libraries/RBL_nRF8001/RBL_nRF8001.h:17,
                 from /Users/atf/Documents/Arduino/libraries/RBL_nRF8001/RBL_nRF8001.cpp:14:
/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.h:38:74: note: '__c' was declared here
 #define F(string_literal) (reinterpret_cast<const __FlashStringHelper *>(PSTR(string_literal)))
                                                                          ^
/Users/atf/Documents/Arduino/libraries/RBL_nRF8001/RBL_nRF8001.cpp:388:32: note: in expansion of macro 'F'
                 Serial.println(F("Advertising started"));
                                ^
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
